import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Nunito, Inter } from 'next/font/google'
import { TooltipProvider } from "@/components/ui/tooltip"

import './globals.css'

const nunito = Nunito({
variable: '--font-nunito',
  subsets: ['latin'],
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Beboy's Kagawad's Best Eatery",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${nunito.variable} ${inter.variable} h-full antialiased bg-bg-muted`}>
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
              <TooltipProvider>
                {children}
              </TooltipProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}